@rootUrl = http://localhost:8000/api/v1
@userApi = {{rootUrl}}/users
@categoryApi = {{rootUrl}}/categories

# ======== user API
###login user
POST {{userApi}}/sign-in
Content-Type: application/json

{
    "email": "b@b.com",
    "password": "aA1234"
}

###get user profile
GET {{userApi}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDUyODA2ODIsImV4cCI6MTcwNTI4MTU4Mn0.yS4Q1hV2Bvx9VC9g8PnAJb0V75gDgwZ-eMdDwJYTAiU

###request otp
POST {{userApi}}/request-otp
Content-Type: application/json

{
    "email": "a@a.com"
}

### C
POST {{categoryApi}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDU0NjgxNjcsImV4cCI6MTcwNTQ2OTA2N30.CJ_ufMwUyDkJmuW_PdPWa-9B2yjuLcZTkZAO0BRbrCo
Content-Type: application/json

{
    "title": "Jewlery"
}

###R
GET {{categoryApi}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDU0NjgxNjcsImV4cCI6MTcwNTQ2OTA2N30.CJ_ufMwUyDkJmuW_PdPWa-9B2yjuLcZTkZAO0BRbrCo

###U
PUT {{categoryApi}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDU0NjgxNjcsImV4cCI6MTcwNTQ2OTA2N30.CJ_ufMwUyDkJmuW_PdPWa-9B2yjuLcZTkZAO0BRbrCo

{
    "_id": "65a76125a1de34ff5ea9d184",
    "title": "Women Shoes",
    "status": "active"
}

###D
DELETE {{categoryApi}}/65a602fb1fa06d6b536487ff
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDUzNzkxMDUsImV4cCI6MTcwNTM4MDAwNX0.QJ5o8V_hWDH62YyiAXsuex86ec9CVgmEyls90VI7UcA



