@rootUrl = http://localhost:8000/api/v1
@userApi = {{rootUrl}}/users
@categoryApi = {{rootUrl}}/categories
@productApi = {{rootUrl}}/products

# ======== user API
###login user
POST {{userApi}}/sign-in
Content-Type: application/json

{
    "email": "b@b.com",
    "password": "aA1234"
}

###get user profile
GET {{userApi}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDUyODA2ODIsImV4cCI6MTcwNTI4MTU4Mn0.yS4Q1hV2Bvx9VC9g8PnAJb0V75gDgwZ-eMdDwJYTAiU

###request otp
POST {{userApi}}/request-otp
Content-Type: application/json

{
    "email": "a@a.com"
}

###Update user profile
PATCH {{userApi}}/user-profile
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDU2NDEzMTksImV4cCI6MTcwNTY0MjIxOX0.UllvZTihG3fB7wEIWInIttytuktICNqPsP21ks43WcM
Content-Type: application/json

{
    "_id": "65a47133ebc597c33989c325",
    "fName": "Gaurav",
    "lName": "Shreenet",
    "phone": "0451352524",
    "address": "32 Brittain Crescent, Hillsdale NSW"
}

### C
POST {{categoryApi}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDU0NjgxNjcsImV4cCI6MTcwNTQ2OTA2N30.CJ_ufMwUyDkJmuW_PdPWa-9B2yjuLcZTkZAO0BRbrCo
Content-Type: application/json

{
    "title": "Jewlery"
}

###R
GET {{categoryApi}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDU0NjgxNjcsImV4cCI6MTcwNTQ2OTA2N30.CJ_ufMwUyDkJmuW_PdPWa-9B2yjuLcZTkZAO0BRbrCo

###U
PUT {{categoryApi}}
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDU2MzM3ODIsImV4cCI6MTcwNTYzNDY4Mn0.UUUtFt2TkVXVtSHxdaEegF0KIlsKtmIF2vxm8sax86o

{
    "_id": "65a76125a1de34ff5ea9d184",
    "title": "Women Shoe",
    "status": "active"
}

###D
DELETE {{categoryApi}}/65a602fb1fa06d6b536487ff
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDUzNzkxMDUsImV4cCI6MTcwNTM4MDAwNX0.QJ5o8V_hWDH62YyiAXsuex86ec9CVgmEyls90VI7UcA

# ==================Product

###CRUD
POST {{productApi}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAYi5jb20iLCJpYXQiOjE3MDU4ODAzMDMsImV4cCI6MTcwNTg4MTIwM30.O_BHz2QlRZgUvxJL8jOTxoO0VUQPlvQfAad25reEK2k
Content-Type: application/json

{
    "name": "Nike AirMax",
    "parentCatId": "65a76125a1de34ff5ea9d184",
    "sku": "N-AM10",
    "price": 220,
    "qty": 120,
    "salesPrice": 0,
    "description": "Air Max shoes are identified by their midsoles incorporating flexible urethane pouches filled with pressurized gas, visible from the exterior of the shoe and intended to provide cushioning to the underfoot. Air Max was conceptualized by Tinker Hatfield, who initially worked for Nike designing stores. Nike, Inc.",
    "salesStartDate": "SHORTSTR",
    "salesEndDate": "SHORTSTR"
}

